=== AnsonThomas22/Lab4-lab5_xml/lab4/lab4.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Hospital (Patient+, MedicalRecords+, Nurse+, Appointment+, Facility+, Billing+, InsuranceCompany+, Feedback+)>


<!ELEMENT Patient (Name, PhoneNumber, Date_of_Birth, Gender, Address, BloodGroup, Allergies)>
<!ATTLIST Patient Patient_ID ID #REQUIRED>
<!ELEMENT Name (First_Name, Last_Name)>
<!ELEMENT First_Name (#PCDATA)>
<!ELEMENT Last_Name (#PCDATA)>
<!ELEMENT PhoneNumber (#PCDATA)>
<!ELEMENT Date_of_Birth (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT BloodGroup (#PCDATA)>
<!ELEMENT Allergies (#PCDATA)>


<!ELEMENT MedicalRecords (PatientID, DoctorID, Diagnosis, Treatment, LastVisit, Medications)>
<!ATTLIST MedicalRecords RecordID ID #REQUIRED>
<!ELEMENT PatientID (#PCDATA)>
<!ELEMENT DoctorID (#PCDATA)>
<!ELEMENT Diagnosis (#PCDATA)>
<!ELEMENT Treatment (#PCDATA)>
<!ELEMENT LastVisit (#PCDATA)>
<!ELEMENT Medications (#PCDATA)>


<!ELEMENT Nurse (Name, PhoneNumber, Department, Experience, Shift, Certification)>
<!ATTLIST Nurse NurseID ID #REQUIRED>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Experience (#PCDATA)>
<!ELEMENT Shift (#PCDATA)>
<!ELEMENT Certification (#PCDATA)>


<!ELEMENT Appointment (PatientID, DoctorID, AppointmentDate, Purpose, Location, Status, FollowUpRequired)>
<!ATTLIST Appointment AppointmentID ID #REQUIRED>
<!ELEMENT AppointmentDate (#PCDATA)>
<!ELEMENT Purpose (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT FollowUpRequired (#PCDATA)>


<!ELEMENT Facility (NameFa, Location, Capacity, Type, ParkingAvailable, OperatingRooms)>
<!ATTLIST Facility FacilityID ID #REQUIRED>
<!ELEMENT NameFa (#PCDATA)>
<!ELEMENT Capacity (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT ParkingAvailable (#PCDATA)>
<!ELEMENT OperatingRooms (#PCDATA)>


<!ELEMENT Billing (PatientID, Amount, PaymentStatus, DateIssued, PaymentMethod)>
<!ATTLIST Billing BillID ID #REQUIRED>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT PaymentStatus (#PCDATA)>
<!ELEMENT DateIssued (#PCDATA)>
<!ELEMENT PaymentMethod (#PCDATA)>


<!ELEMENT InsuranceCompany (Name, PhoneNumber, Address, CoverageTypes, PolicyDetails, CustomerReview, ClaimsProcessingTime)>
<!ATTLIST InsuranceCompany CompanyID ID #REQUIRED>
<!ELEMENT CoverageTypes (#PCDATA)>
<!ELEMENT PolicyDetails (#PCDATA)>
<!ELEMENT CustomerReview (#PCDATA)>
<!ELEMENT ClaimsProcessingTime (#PCDATA)>

<!ELEMENT Feedback (Feedrating,Description)>
<!ATTLIST Feedback FeedbackID ID #REQUIRED>
<!ELEMENT Feedrating (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

=== AnsonThomas22/Lab4-lab5_xml/lab4/lab4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hospital SYSTEM "lab4.dtd">
<?xml-model href="lab4.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<?xml-stylesheet type="text/xsl" href="lab4.xsl"?>

<Hospital>
    <Patient Patient_ID="A12">
        <Name>
            <First_Name>Anson</First_Name>
            <Last_Name>Thomas</Last_Name>
        </Name>
        <PhoneNumber>123445556</PhoneNumber>
        <Date_of_Birth>12/12</Date_of_Birth>
        <Gender>Male</Gender>
        <Address> No.10, 5th cross</Address>
        <BloodGroup>O+</BloodGroup>
        <Allergies>None</Allergies>
    </Patient>

    <MedicalRecords RecordID="A1001">
        <PatientID>A12</PatientID>
        <DoctorID>101</DoctorID>
        <Diagnosis>Coronary Artery Disease</Diagnosis>
        <Treatment>Bypass Surgery</Treatment>
        <LastVisit>2024-08-01</LastVisit>
        <Medications>Aspirin, Beta-blockers</Medications>
    </MedicalRecords>

    <Nurse NurseID="A301">
        <Name>
            <First_Name>Lola</First_Name>
            <Last_Name>Thomas</Last_Name>
        </Name>
        <PhoneNumber>0987654321</PhoneNumber>
        <Department>Cardiology</Department>
        <Experience>5</Experience>
        <Shift>Day</Shift>
        <Certification>RN, BSN</Certification>
    </Nurse>

    <Appointment AppointmentID="A4001">
        <PatientID>A12</PatientID>
        <DoctorID>1011</DoctorID>
        <AppointmentDate>2024-08-05T10:00:00</AppointmentDate>
        <Purpose>Follow-up</Purpose>
        <Location>2nd Floor, Room 201</Location>
        <Status>Scheduled</Status>
        <FollowUpRequired>Yes</FollowUpRequired>
    </Appointment>

    <Facility FacilityID="A5001">
        <NameFa>Main Hospital</NameFa>
        <Location>Main Street, Building 3</Location>
        <Capacity>200</Capacity>
        <Type>Hospital</Type>
        <ParkingAvailable>Yes</ParkingAvailable>
        <OperatingRooms>10</OperatingRooms>
    </Facility>

    <Billing BillID="A6001">
        <PatientID>A12</PatientID>
        <Amount>50000.00</Amount>
        <PaymentStatus>Pending</PaymentStatus>
        <DateIssued>2024-08-06</DateIssued>
        <PaymentMethod>Insurance</PaymentMethod>
    </Billing>

    <InsuranceCompany CompanyID="A123">
        <Name>
            <First_Name>Anson</First_Name>
            <Last_Name>Thomas</Last_Name>
        </Name>
        <PhoneNumber>123344555</PhoneNumber>
        <Address>hello</Address>
        <CoverageTypes>hhhh</CoverageTypes>
        <PolicyDetails>kkkk</PolicyDetails>
        <CustomerReview>nice</CustomerReview>  
        <ClaimsProcessingTime>12</ClaimsProcessingTime>  



    </InsuranceCompany>

    <Feedback FeedbackID="A8001">
        <Feedrating>5</Feedrating>
        <Description>Good</Description>
    </Feedback>
</Hospital>
